### ISSUE TITLE
Peer assessment for Capstone Project how to choose the topic

### ISSUE THREAD

**Issue by libinandrews** [dheerajnbhat/Data-Science-Sturdy-guide#2]
Hi 

Am also doing the course but I don't know which topic to choose for this project.
Can you please help me out.

**Comment by dheerajnbhat** [comment]
Hi, you can first choose a problem statement which you want/interested to work on. You can pick a specific domain and then look for use cases also. Based on the problem statement, look up for the dataset and see if its available anywhere like kaggle etc. If data is not available, you can create your own custom dataset from raw data through Data scraping techniques using beautifulsoup4 etc. Broadly speaking, any Data science project should have the following:
  - Problem Statement
  - Data Analysis
  - Data Visualization
  - Training Methodology
  - Results and Inference

**Comment by libinandrews** [comment]
Thanks Broo
