### ISSUE TITLE
requesting Dataset

### ISSUE THREAD

**Issue by kiranshanmugam2001** [dheerajnbhat/Data-Science-Sturdy-guide#3]
Hi @dheerajnbhat this is Kirankumar Shanmugam, a Data scientist enthusiast from India,I came across your work on Github "recommending a business at a particular tourist venue",it was really  nice work , and i'm currently doing my CAPSTONE project to fulfill my PG course, for that i **need the Dataset** used in your project to take your project to the next step.

**Comment by dheerajnbhat** [comment]
Hi @kiranshanmugam2001, unfortunately I do not have this dataset right now. I had scraped the data from https://en.wikipedia.org/wiki/List_of_districts_in_India. You can create the dataset by scraping this website using beautifulsoup4 and extract relevant columns. 

I hope this helpful

**Comment by kiranshanmugam2001** [comment]
But you didn't provided the code for the web scrapping part.

**Comment by dheerajnbhat** [comment]
As I commented earlier, you can use beautifulsoup4 python package to scrape the website and extract relevant columns as per your requirement

**Comment by kiranshanmugam2001** [comment]
got you , thanks for your reply
